"""add_current_crop_tracking_to_user

Revision ID: 84d9f9ee91bd
Revises: 4453de644f3f
Create Date: 2025-06-01 10:17:47.110782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d9f9ee91bd'
down_revision: Union[str, None] = '4453de644f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_crop_tracking_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_users_refresh_token'), table_name='users')
    op.create_foreign_key(None, 'users', 'user_crop_tracking', ['current_crop_tracking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_refresh_token'), 'users', ['refresh_token'], unique=True)
    op.drop_column('users', 'current_crop_tracking_id')
    # ### end Alembic commands ###
