"""Add Firebase auth fields to User model

Revision ID: 9cf3eb530a90
Revises: fix_nullable_fields
Create Date: 2025-06-25 17:02:42.073175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cf3eb530a90'
down_revision: Union[str, None] = 'fix_nullable_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firebase_users_email'), table_name='firebase_users')
    op.drop_index(op.f('ix_firebase_users_firebase_uid'), table_name='firebase_users')
    op.drop_index(op.f('ix_firebase_users_id'), table_name='firebase_users')
    op.drop_index(op.f('ix_firebase_users_phone_number'), table_name='firebase_users')
    op.drop_index(op.f('ix_firebase_users_username'), table_name='firebase_users')
    op.drop_table('firebase_users')
    op.alter_column('crop_translations', 'cultivated_in',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('crop_translations', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('crop_translations', 'variety',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'firebase_uid')
    op.alter_column('crop_translations', 'variety',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('crop_translations', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('crop_translations', 'cultivated_in',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.create_table('firebase_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('farm_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('current_crop_tracking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notification_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_crop_tracking_id'], ['user_crop_tracking.id'], name=op.f('firebase_users_current_crop_tracking_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('firebase_users_pkey'))
    )
    op.create_index(op.f('ix_firebase_users_username'), 'firebase_users', ['username'], unique=True)
    op.create_index(op.f('ix_firebase_users_phone_number'), 'firebase_users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_firebase_users_id'), 'firebase_users', ['id'], unique=False)
    op.create_index(op.f('ix_firebase_users_firebase_uid'), 'firebase_users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_firebase_users_email'), 'firebase_users', ['email'], unique=True)
    # ### end Alembic commands ###
