"""updated fcm token schema

Revision ID: cf1915d5a345
Revises: e054141e5c3a
Create Date: 2025-07-02 12:25:03.417888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1915d5a345'
down_revision: Union[str, None] = 'e054141e5c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fcm_tokens_token_key'), 'fcm_tokens', type_='unique')
    op.drop_index(op.f('ix_fcm_tokens_user_id'), table_name='fcm_tokens')
    op.create_index(op.f('ix_fcm_tokens_user_id'), 'fcm_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_fcm_tokens_token'), 'fcm_tokens', ['token'], unique=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_fcm_tokens_token'), table_name='fcm_tokens')
    op.drop_index(op.f('ix_fcm_tokens_user_id'), table_name='fcm_tokens')
    op.create_index(op.f('ix_fcm_tokens_user_id'), 'fcm_tokens', ['user_id'], unique=True)
    op.create_unique_constraint(op.f('fcm_tokens_token_key'), 'fcm_tokens', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
